file=open('dict_Example5.py','r')
data=file.readline()
print(data)
data=file.readline()
print(data)
data=file.readline(20)
print(data)
# data=file.readline()
# print(data)
# data=file.readline()
# print(data)
file.close()